
FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install postgresql postgresql-contrib --yes

USER postgres

RUN /etc/init.d/postgresql start &&\
    psql --command "CREATE USER admin WITH SUPERUSER PASSWORD '1Ctdfcnjgjkm';" &&\
    createdb -O admin product_srv &&\
    createdb -O admin identity_srv &&\
    createdb -O admin file_srv &&\
    createdb -O admin checkout_srv &&\
    createdb -O admin comment_srv
#    createdb -O admin customer_srv &&\
#    createdb -O admin seller_srv &&\
#    createdb -O admin promotion_srv

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/10/main/pg_hba.conf

RUN echo "listen_addresses='*'" >> /etc/postgresql/10/main/postgresql.conf

EXPOSE 5432

VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

CMD ["/usr/lib/postgresql/10/bin/postgres", "-D", "/var/lib/postgresql/10/main", "-c", "config_file=/etc/postgresql/10/main/postgresql.conf"]
