
# BUILD APP
FROM node:18-alpine3.16

RUN npm install -g npm@latest
RUN npm config set package-lock false

WORKDIR /server

COPY ./sellgar.service/                ./

RUN yarn
RUN yarn build

# BUILD APPLICATION
WORKDIR /server/apps/checkout_srv
ENTRYPOINT ["npm", "run", "start"]
