
# BUILD APP
FROM node:16-alpine3.11 as ui

RUN apk update && apk add bash
RUN npm install -g npm@latest
RUN npm config set package-lock false

WORKDIR /admin

COPY ../sellgar.admin.ui/             ./

RUN yarn

RUN chmod +x ./builder.sh
RUN ./builder.sh

# BUILD APPLICATION
WORKDIR /admin/app/client
RUN ["yarn", "run", "build"]

# START NGINX
FROM nginx

COPY --from=ui /admin/app/client/build /admin

WORKDIR /etc/nginx

CMD ["nginx", "-g", "daemon off;"]
