
# BUILD APP
FROM node:18-alpine3.15 as ui

RUN npm install -g npm@latest
RUN npm config set package-lock false

WORKDIR /client

COPY ./sellgar.client.ui/                ./

RUN yarn

RUN chmod +x ./builder.sh
RUN ./builder.sh

# BUILD APPLICATION
WORKDIR /client/apps/client
ENTRYPOINT ["npm", "run", "build"]
ENTRYPOINT ["npm", "run", "start"]
