# BUILD APP
FROM node:18-alpine3.15 as build

WORKDIR /client

COPY ./sellgar.client.ui/                ./

RUN which yarn || npm i yarn -g

#Enabled yarn audit
RUN yarn --frozen-lockfile
RUN yarn build


FROM node:18-alpine3.15

COPY --from=build /client /client

# BUILD APPLICATION
WORKDIR /client/apps/client
ENTRYPOINT ["yarn", "start"]
