
# BUILD APP
FROM node:18-alpine3.15

RUN npm install -g npm@latest
RUN npm config set package-lock false

WORKDIR /server

COPY ./sellgar.service/                ./

RUN yarn

RUN chmod +x ./builder.sh
RUN ./builder.sh

# BUILD APPLICATION
WORKDIR /server/apps/checkout_srv
ENTRYPOINT ["npm", "run", "start"]
