
# BUILD APP
FROM node:18-alpine3.15

RUN npm install -g npm@latest
RUN npm config set package-lock false

WORKDIR /gateway

COPY ./sellgar.gateway/                ./

RUN yarn

RUN chmod +x ./builder.sh
RUN ./builder.sh

# BUILD APPLICATION
WORKDIR /gateway/apps/admin_gw
ENTRYPOINT ["yarn", "run", "start"]
