
# BUILD APP
FROM node:18-alpine3.15 as ui

RUN npm install -g npm@latest
RUN npm config set package-lock false

WORKDIR /server

COPY ./sellgar.service/                ./

RUN yarn

RUN chmod +x ./builder.sh
RUN ./builder.sh

WORKDIR /server/apps/identity_srv

ENTRYPOINT ["yarn", "run", "start"]
