
# BUILD APP
FROM node:15-alpine

RUN npm install -g npm@latest
RUN npm config set package-lock false

WORKDIR /app

COPY ./sellgar.gateway/                ./

RUN yarn

RUN chmod +x ./builder.sh
RUN ./builder.sh

WORKDIR /gateway/apps/admin_gw

ENTRYPOINT ["yarn", "run", "start"]
