
# BUILD APP
FROM node:16-alpine3.11

RUN npm install -g npm@latest
RUN npm config set package-lock false

WORKDIR /server

COPY ./sellgar.server/                ./

RUN yarn

RUN chmod +x ./builder.sh
RUN ./builder.sh

WORKDIR /server/apps/identity_srv

ENTRYPOINT ["yarn", "run", "start"]
